"""Core data types for reference-DAG construction and unified hallucinations."""

from .editing_schemas import (
    ADDITION_EDITING_SCHEMA,
    ADDITION_STATE_SCHEMA,
    DELETION_EDITING_SCHEMA,
    DELETION_STATE_SCHEMA,
    EDITING_SCHEMA_DEFINITIONS,
    EDITING_STATE_SCHEMAS,
    SUBSTITUTION_EDITING_SCHEMA,
    SUBSTITUTION_STATE_SCHEMA,
    EditingStateSchema,
    editing_schema_for,
    state_schema_for,
)
from .enums import (
    ComparatorKind,
    DependencyType,
    EditingSubtask,
    MutationCategory,
    MutationTargetKind,
    NodeRole,
    Severity,
    ValidationStage,
    ValueProvenance,
    ValueType,
    Visibility,
)
from .errors import (
    ArtifactValidationError,
    DomainValidationError,
    ValidationIssue,
    ValidationReport,
)
from .molecules import FragmentPolicy, MainFragment, MoleculeDescriptors
from .mutations import (
    InjectedHallucination,
    PlannedMutation,
    RenderedHallucination,
    RenderedMention,
    UnifiedHallucinationPlan,
)
from .records import DetectorInput
from .state_dag import (
    ClaimValue,
    FrozenMap,
    StateDAG,
    StateEdge,
    StateNodeSpec,
    StateSchema,
    deep_freeze,
)

__all__ = [
    "ADDITION_EDITING_SCHEMA",
    "ADDITION_STATE_SCHEMA",
    "ArtifactValidationError",
    "ClaimValue",
    "ComparatorKind",
    "DELETION_EDITING_SCHEMA",
    "DELETION_STATE_SCHEMA",
    "DependencyType",
    "DetectorInput",
    "DomainValidationError",
    "EDITING_SCHEMA_DEFINITIONS",
    "EDITING_STATE_SCHEMAS",
    "EditingStateSchema",
    "EditingSubtask",
    "FragmentPolicy",
    "FrozenMap",
    "InjectedHallucination",
    "MainFragment",
    "MoleculeDescriptors",
    "MutationCategory",
    "MutationTargetKind",
    "NodeRole",
    "PlannedMutation",
    "RenderedHallucination",
    "RenderedMention",
    "SUBSTITUTION_EDITING_SCHEMA",
    "SUBSTITUTION_STATE_SCHEMA",
    "Severity",
    "StateDAG",
    "StateEdge",
    "StateNodeSpec",
    "StateSchema",
    "UnifiedHallucinationPlan",
    "ValidationIssue",
    "ValidationReport",
    "ValidationStage",
    "ValueProvenance",
    "ValueType",
    "Visibility",
    "deep_freeze",
    "editing_schema_for",
    "state_schema_for",
]
