"""Canonical character annotations and token projections."""

from .char_annotations import (
    CHAR_ANNOTATION_BUILDER_VERSION,
    CharAnnotationBuilder,
    CharAnnotationBuildError,
    CharAnnotationBuildResult,
    EventAnnotationLink,
    UnlocalizedOmission,
    build_char_annotations,
    derive_evidence_relations,
    is_pure_omission,
)
from .char_spans import (
    CharSpan,
    MentionSpan,
    span_text,
    validate_char_span,
    validate_mention_spans,
    validate_non_overlapping_spans,
)
from .token_projection import (
    ACTIVATION_ALIGNMENT,
    TOKEN_PROJECTION_VERSION,
    ChemDFMRTokenProjector,
    DetectorCoordinateMap,
    FastOffsetTokenizer,
    FastTokenization,
    TokenLabelSetWriter,
    TokenProjectionError,
    project_char_annotations,
    rebase_char_annotations,
)

__all__ = [
    "ACTIVATION_ALIGNMENT",
    "CHAR_ANNOTATION_BUILDER_VERSION",
    "TOKEN_PROJECTION_VERSION",
    "CharAnnotationBuildError",
    "CharAnnotationBuildResult",
    "CharAnnotationBuilder",
    "CharSpan",
    "ChemDFMRTokenProjector",
    "DetectorCoordinateMap",
    "EventAnnotationLink",
    "FastOffsetTokenizer",
    "FastTokenization",
    "MentionSpan",
    "TokenLabelSetWriter",
    "TokenProjectionError",
    "UnlocalizedOmission",
    "build_char_annotations",
    "derive_evidence_relations",
    "is_pure_omission",
    "project_char_annotations",
    "rebase_char_annotations",
    "span_text",
    "validate_char_span",
    "validate_mention_spans",
    "validate_non_overlapping_spans",
]
